import fs from 'node:fs';
import path from 'node:path';
import { ROOT } from './config.js';
import { dashboardData } from './dashboard.js';

// Precompute the dashboard payload to a static JS module that the Vercel
// serverless /api/data function imports. The Playwright collection can't run on
// Vercel, so the deployed app reads this snapshot; the LOCAL job regenerates it
// after each `build`/refresh. Live FX is added per-request in the function.
export function writeSnapshot() {
  const data = dashboardData();
  data.meta = { ...data.meta, snapshotAt: new Date().toISOString() };
  delete data.meta.fx; // FX is fetched live in the serverless function
  const out = path.join(ROOT, 'api', '_data', 'snapshot.js');
  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, '// AUTO-GENERATED by `node src/cli.js snapshot`. Do not edit.\nexport default ' + JSON.stringify(data) + ';\n');
  return { out, declarations: data.meta.declarations, goodsLines: data.meta.goodsLines, bytes: fs.statSync(out).size };
}
